base_url = "https://rescue-respiration.github.io"
title = "Rescue Respiration"
description = "Affordable, open-source Ventilators for Everyone."
default_language = "en"
compile_sass = true
build_search_index = true
minify_html = false


[markdown]
highlight_code = true
external_links_no_follow = true
external_links_no_referrer = true

[extra]
logo_name = "Rescue Respiration"
logo_path = "lung-red.svg"
external_nav = [
    { title = "Github", link = "https://github.com/rescue-respiration/", weight=4}
]
